---
- name: Cleanup queues
  hosts: control[0]
  gather_facts: false

  tasks:
    - name: Purge notifications.info queue
      ansible.builtin.command: docker exec -t rabbitmq rabbitmqctl purge_queue notifications.info
      async: 120
      poll: 5
      changed_when: true

    - name: Purge notifications.error queue
      ansible.builtin.command: docker exec -t rabbitmq rabbitmqctl purge_queue notifications.error
      async: 120
      poll: 5
      changed_when: true
